service: line-bot-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1
  memorySize: 512
  timeout: 30
  environment:
    LINE_CHANNEL_SECRET: ${env:LINE_CHANNEL_SECRET}
    LINE_CHANNEL_TOKEN: ${env:LINE_CHANNEL_TOKEN}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: bot/hello
          method: post

package:
  include:
    - handler.rb

plugins:
  - serverless-ruby-package