service: line-bot-test # NOTE: update this with your service name

provider:
  name: aws
  runtime: ruby2.5
  region: ap-northeast-1
  memorySize: 128
  timeout: 30
  environment:
    LINE_CHANNEL_SECRET: ${env:LINE_CHANNEL_SECRET}
    LINE_CHANNEL_TOKEN: ${env:LINE_CHANNEL_TOKEN}
    MY_LINE_USER_ID: ${env:MY_LINE_USER_ID}
    CITY_ID: 130010 ## 東京(http://weather.livedoor.com/forecast/rss/primary_area.xml)

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: bot/hello
          method: post
  pushMessage:
    handler: pushMessage.weather
    events:
      - schedule: cron(0 13 * * ? *)


package:
  include:
    - handler.rb
    - pushMessage.rb
    - lib/*

plugins:
  - serverless-ruby-package